include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    non_constant_identifier_names: false
    no_leading_underscores_for_local_identifiers: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false